# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    working_directory: ~/luxmed
    docker:
      - image: cimg/openjdk:21.0
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: company_db
          POSTGRES_PASSWORD: 1234
    steps:
      - checkout
      - run:
          name: Install dockerize
          command: |
            apk add --no-cache dockerize
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test -Dtest=!IntegrationTest
      - persist_to_workspace:
          root: .
          paths:
            - target

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
