version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:21-jdk
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
